name: RSpec

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
        bundler-cache: true
    - name: Setup Ruby
      run: |
        gem install bundler:2.1.4
        bundle install --quiet --jobs 4 --retry 3
    - name: Setup Database
      env:
        RAILS_ENV: test
        MYSQL_ROOT_PASSWORD: root
      run: |
        cp config/database_ci.yml config/database.yml
        ./bin/rails db:create
        ./bin/rails db:migrate
    - name: Run tests
      run: bundle exec rspec